title: Mein Portfolio & Wiki
author: 
email: 
description: Mein pers√∂nliches Portfolio, meine Projekte und Notizen
baseurl: "" 
url: "https://werzingerma.github.io" 

github_username: werzingerma
#linkedin_username: maximilian-werzinger-8b7939341

# Build-Einstellungen
theme: null 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation im Header
header_pages:
  - index.md
  - projects/index.md
  - notes/index.md

# Permalink-Struktur
permalink: /:categories/:title/

# Ausgeschlossene Dateien
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
